# Generated by Django 5.0.2 on 2024-02-24 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип оборудования')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('id_number', models.CharField(max_length=10, verbose_name='Инвентарный номер')),
                ('sale_date', models.DateField(default=datetime.date(2024, 1, 1), verbose_name='Дата покупки')),
                ('price', models.BooleanField(max_length=10, verbose_name='Цена покупки')),
                ('is_working', models.BooleanField(default=True, verbose_name='Работает')),
                ('testing', models.BooleanField(default=False, verbose_name='Доступно для тестирования')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['type', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('department', models.CharField(max_length=50, verbose_name='Отдел')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('remote', models.BooleanField(default=False, verbose_name='Удаленщик')),
                ('is_working', models.BooleanField(default=True, verbose_name='Работает')),
                ('city', models.CharField(default='Москва', max_length=50, verbose_name='Город')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
