# Generated by Django 5.0.2 on 2024-02-24 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='jobing_at',
            field=models.DateField(default=datetime.date(2020, 1, 1), verbose_name='Дата трудоустройства'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.FloatField(max_length=10, verbose_name='Цена покупки'),
        ),
    ]
