# Generated by Django 5.0.2 on 2024-04-20 17:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqlog', '0003_alter_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='last_name', unique=True),
        ),
    ]
