# Generated by Django 5.0.2 on 2024-03-12 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqlog', '0003_department_alter_person_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='get_equipments', to='eqlog.person', verbose_name='Сотрудник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_persons', to='eqlog.department', verbose_name='Отдел'),
        ),
    ]
