# Generated by Django 5.0.2 on 2024-04-20 17:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqlog', '0004_alter_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='id_number', unique=True),
        ),
    ]
