# Generated by Django 5.0.2 on 2024-04-20 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqlog', '0006_remove_eqlog_id_number_eqlog_field_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eqlog',
            new_name='EqlogEquipment',
        ),
        migrations.RenameField(
            model_name='eqlogequipment',
            old_name='id_equipments',
            new_name='id_equipment',
        ),
        migrations.CreateModel(
            name='EqlogPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(verbose_name='Старое значение')),
                ('new_value', models.TextField(verbose_name='Новое значение')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_person', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
