# Generated by Django 5.0.2 on 2024-04-28 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqlog', '0007_rename_eqlog_eqlogequipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqlogequipment',
            name='equipment',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, related_name='get_equipments', to='eqlog.equipment'),
            preserve_default=False,
        ),
    ]
