# Generated by Django 5.0.2 on 2024-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqlog', '0009_remove_eqlogperson_user_eqlog_delete_eqlogequipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqlog',
            name='logged_value',
            field=models.TextField(default=1, verbose_name='Журналируемое значение'),
            preserve_default=False,
        ),
    ]
